"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Waves,BusFront,Ship,ShipWheel,Sailboat,ArrowUpRight,ArrowLeft,Plus,Minus,LocateFixed,Maximize,Minimize,RefreshCw,Info,X,Clock3,Layers3,ChevronRight,MapPin,Radio,ChevronDown} from "lucide-react";
import TrafficMap,{type MapHandle} from "./traffic-map";
import {kinds,places,stops,oldPosition,age,time,type Kind,type Vehicle,type Feed} from "../lib/traffic";
const icons={bus:BusFront,ferry:Ship,boat:Sailboat,ship:ShipWheel};
type Call={realtime:boolean;aimedDepartureTime:string;expectedDepartureTime:string;destinationDisplay:{frontText:string};quay:{name:string};serviceJourney:{journeyPattern:{line:{publicCode:string;transportMode:string}}}};
function useFeed(source:string){
 const [feed,setFeed]=useState<Feed|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false),[tick,setTick]=useState(0);
 useEffect(()=>{let active=true;const controller=new AbortController();
 async function load(){setLoading(true);try{const r=await fetch("/api/traffic?source="+source,{signal:controller.signal});if(!r.ok)throw Error();const j=await r.json();if(active){setFeed(j as Feed);setError(false);}}catch{if(active)setError(true);}finally{if(active)setLoading(false);}}
 load();const interval=setInterval(()=>{if(!document.hidden)load();},source==="bus"?30000:300000);
 return()=>{active=false;controller.abort();clearInterval(interval);};},[source,tick]);
 return {feed,loading,error,reload:()=>setTick(t=>t+1)};
}
export default function Home(){
 const bus=useFeed("bus"),ais=useFeed("ais"),mapRef=useRef<MapHandle>(null),dialog=useRef<HTMLDialogElement>(null);
 const [place,setPlace]=useState("Hele området"),[enabled,setEnabled]=useState<Record<Kind,boolean>>({bus:true,ferry:true,boat:true,ship:true}),[selected,setSelected]=useState<Vehicle|null>(null),[three,setThree]=useState(false),[full,setFull]=useState(false),[now,setNow]=useState(Date.now()),[visible,setVisible]=useState<string[]|null>(null),[tab,setTab]=useState("oversikt"),[expanded,setExpanded]=useState(false),[stop,setStop]=useState(stops[0].id),[departures,setDepartures]=useState<{calls:Call[];fetched:string}|null>(null),[depError,setDepError]=useState(false),[depLoading,setDepLoading]=useState(true);
 const vehicles=[...(bus.feed?.vehicles||[]),...(ais.feed?.vehicles||[])];
 const inView=vehicles.filter(v=>(visible===null||visible.includes(v.id)));
 const shown=inView.filter(v=>enabled[v.kind]);
 const selectedNow=vehicles.find(v=>v.id===selected?.id)||selected;
 const someError=bus.error||ais.error;const updating=bus.loading||ais.loading;
 const received=[bus.feed?.fetched,ais.feed?.fetched].filter(Boolean).sort().at(-1)||null;
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),15000);const fullscreen=()=>setFull(!!document.fullscreenElement);document.addEventListener("fullscreenchange",fullscreen);return()=>{clearInterval(id);document.removeEventListener("fullscreenchange",fullscreen);};},[]);
 useEffect(()=>{let active=true;const controller=new AbortController();setDepartures(null);setDepError(false);
 async function load(){setDepLoading(true);try{const r=await fetch("/api/departures?stop="+encodeURIComponent(stop),{signal:controller.signal});if(!r.ok)throw Error();const j=await r.json();if(active){setDepartures(j as {calls:Call[];fetched:string});setDepError(false);}}catch{if(active)setDepError(true);}finally{if(active)setDepLoading(false);}}
 load();const id=setInterval(()=>{if(!document.hidden)load();},30000);return()=>{active=false;controller.abort();clearInterval(id);};},[stop]);
 const onVisible=useCallback((ids:string[])=>setVisible(previous=>previous?.join()===ids.join()?previous:ids),[]);
 function go(name:string){setPlace(name);mapRef.current?.go(name);setSelected(null);if(name==="Hele området")setThree(false);const index=places.findIndex(p=>p.name===name);if(index>=0)setStop(stops[[0,2,3,4,5,6][index]].id);}
 function select(v:Vehicle){setSelected(v);}
 function chooseStop(id:string){setStop(id);setTab("avganger");setExpanded(true);setSelected(null);}
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setFull(false);}}
 return <main className="app-shell">
 <header className="topbar"><div className="brand"><Waves aria-hidden="true"/><div><h1>Nordhordland<span> / </span></h1><p>PÅ SJØ OG LAND</p></div></div><div className="header-center"><span>60° N</span><i/><span>VESTLAND, NORGE</span></div><div className="header-actions"><div className={"connection"+(someError?" warning":"")}><Radio size={16}/><div><strong>{someError?"Delvis tilgjengelig":received?"Trafikkdata tilkoblet":"Kobler til trafikkdata"}</strong><small>{received?"Sist hentet "+time(received):"Entur · AIS"}</small></div></div><button className="icon-button" aria-label="Om kartet og datakildene" onClick={()=>dialog.current?.showModal()}><Info size={21}/></button></div></header>
 <div className="workspace">
 <aside className={"sidebar"+(expanded?" expanded":"")}>
 <button className="mobile-handle" onClick={()=>setExpanded(v=>!v)} aria-expanded={expanded}>Utforsk og avganger <ChevronDown size={18}/></button>
 <div className="sidebar-body"><span className="eyebrow">FRA FJORD TIL FJORD</span><h2>Utforsk Nordhordland</h2>
 <nav className="places" aria-label="Velg kartområde"><button aria-pressed={place==="Hele området"} className={place==="Hele området"?"active":""} onClick={()=>go("Hele området")}><LocateFixed size={16}/>Hele området<span className="key-label">OVERSIKT</span></button>{places.map(p=><button aria-pressed={p.name===place} className={p.name===place?"active":""} onClick={()=>go(p.name)} key={p.name}>{p.name}<ArrowUpRight size={14}/></button>)}</nav>
 <div className="side-tabs" role="tablist" aria-label="Trafikkpanel">{[["oversikt","Kartlag"],["trafikk","Trafikk"],["avganger","Avganger"]].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==="oversikt"&&<div className="tab-content"><div className="section-heading"><h3>Dette vises på kartet</h3><span>{Object.values(enabled).filter(Boolean).length} lag</span></div><div className="layer-list">{kinds.map(k=>{const Icon=icons[k.id];const count=inView.filter(v=>v.kind===k.id).length;return <button key={k.id} className={"layer-row"+(!enabled[k.id]?" off":"")} role="switch" aria-checked={enabled[k.id]} aria-label={k.name+" på kartet"} onClick={()=>setEnabled(e=>({...e,[k.id]:!e[k.id]}))} style={{"--layer-color":k.color} as React.CSSProperties}><span className="layer-icon"><Icon size={21}/></span><span className="layer-text"><strong>{k.name}</strong><small>{k.description}</small></span><span className="layer-count">{(k.id==="bus"?bus:ais).feed?count:"–"}</span><span className="switch"><i/></span></button>})}</div><div className="coverage-note"><MapPin size={15}/><p>Tallene gjelder kartutsnittet. Velg et punkt for å se mer.</p></div>
 <div className="quick-departure"><div><Clock3 size={18}/><h3>Neste avgang</h3></div><p>{stops.find(s=>s.id===stop)?.name}</p>{depLoading&&!departures?<p className="muted">Henter avganger …</p>:departures?.calls.filter(c=>Date.parse(c.expectedDepartureTime||c.aimedDepartureTime)>=now).slice(0,1).map((c,i)=><button key={i} onClick={()=>setTab("avganger")}><span className="route-badge">{c.serviceJourney?.journeyPattern?.line?.publicCode||"–"}</span><span>{c.destinationDisplay?.frontText}<small>{time(c.expectedDepartureTime||c.aimedDepartureTime)} · {c.realtime?"Sanntid":"Rutetid"}</small></span><ChevronRight size={16}/></button>)}{!depLoading&&(depError||!departures?.calls.length)&&<p className="muted">{depError?"Avganger er utilgjengelige nå.":"Ingen avganger de neste seks timene."}</p>}<button className="text-link" onClick={()=>setTab("avganger")}>Se avgangstavle <ArrowUpRight size={15}/></button></div></div>}
 {tab==="trafikk"&&<div className="tab-content"><div className="section-heading"><h3>I kartutsnittet</h3><span>{shown.length} posisjoner</span></div>{shown.length===0&&<p className="empty">{updating?"Henter trafikkdata …":"Ingen posisjoner i utsnittet med valgte kartlag."}</p>}<div className="vehicle-list">{[...shown].sort((a,b)=>(oldPosition(a,now)?1:0)-(oldPosition(b,now)?1:0)||a.name.localeCompare(b.name,"nb")).map(v=>{const Icon=icons[v.kind];return <button key={v.id} className="vehicle-row" onClick={()=>{select(v);mapRef.current?.focus(v);setExpanded(false);}}><Icon size={18} style={{color:kinds.find(k=>k.id===v.kind)?.color}}/><span><strong>{v.name}</strong><small>{v.source==="AIS"?v.destination||"AIS-posisjon":v.destination||v.route}</small><small className={oldPosition(v,now)?"warning":""}>{age(v.updated,now)}</small></span><ChevronRight size={15}/></button>})}</div></div>}
 {tab==="avganger"&&<div className="tab-content"><label className="select-label" htmlFor="stop">Holdeplass eller kai</label><select id="stop" value={stop} onChange={e=>setStop(e.target.value)}>{stops.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><div className="section-heading"><h3>Kommende avganger</h3><span>{depLoading?"Oppdaterer …":time(departures?.fetched||null)}</span></div>{depError&&<p className="empty warning">Avgangene er utilgjengelige nå. Prøver igjen automatisk.</p>}{!departures&&!depError&&<p className="empty">Henter avganger …</p>}{departures&&<div className={"departure-list"+(depError?" stale":"")}>{departures.calls.filter(c=>Date.parse(c.expectedDepartureTime||c.aimedDepartureTime)>=now).map((c,i)=>{const line=c.serviceJourney?.journeyPattern?.line;return <div className="departure" key={i}><span className={"route-badge "+(line?.transportMode==="water"?"water":"")}>{line?.publicCode||"Båt"}</span><span><strong>{c.destinationDisplay?.frontText||"Ukjent destinasjon"}</strong><small>{c.realtime?"Sanntid":"Rutetid"}{depError?" · eldre data":""}</small></span><time>{time(c.expectedDepartureTime||c.aimedDepartureTime)}</time></div>})}{!departures.calls.filter(c=>Date.parse(c.expectedDepartureTime||c.aimedDepartureTime)>=now).length&&<p className="empty">Ingen flere avganger de neste seks timene.</p>}</div>}<a className="text-link external" href="https://www.skyss.no/" target="_blank" rel="noreferrer">Reiseinformasjon hos Skyss <ArrowUpRight size={14}/></a></div>}
 <footer className="sidebar-footer"><div><span className={"feed-light"+(bus.error?" error":"")}/><span>Busser · {bus.error?"utilgjengelig":"hentes hvert 30. sekund"}</span></div><div><span className={"feed-light"+(ais.error?" error":"")}/><span>AIS · {ais.error?"utilgjengelig":"hentes hvert 5. minutt"}</span></div>{(bus.feed?.partial||ais.feed?.partial)&&<p className="warning">Datakilden viser et begrenset utvalg i området.</p>}<button onClick={()=>dialog.current?.showModal()}>Datakilder og dekning <ArrowUpRight size={12}/></button></footer>
 </div></aside>
 <section className="map-stage" aria-label="Kart og trafikk">
 <TrafficMap ref={mapRef} vehicles={vehicles} enabled={enabled} now={now} selected={selectedNow?.id||null} onSelect={select} onStop={chooseStop} onVisible={onVisible}/>
 <div className="map-title"><span className="eyebrow">TRAFIKKART</span><h2>{place==="Hele området"?"Sjøveien. Landeveien.":place}</h2><p>{place==="Hele området"?"Nordhordland og nordsiden av Bergen":"Utforsk trafikken i "+place}</p></div>
 <div className="map-stat"><span>{received?shown.length:"–"}</span><div>posisjoner<br/><small>i kartutsnittet</small></div><button className={"icon-button"+(updating?" spinning":"")} aria-label="Oppdater trafikkdata" disabled={updating} onClick={()=>{bus.reload();ais.reload();}}><RefreshCw size={17}/></button></div>
 <div className="map-controls"><button title="Vend mot nord" aria-label="Vend kartet mot nord" onClick={()=>mapRef.current?.north()}><span className="north-arrow">↑</span><small>N</small></button><i/><button aria-label="Zoom inn" onClick={()=>mapRef.current?.zoom(1)}><Plus size={20}/></button><button aria-label="Zoom ut" onClick={()=>mapRef.current?.zoom(-1)}><Minus size={20}/></button></div>
 {selectedNow&&<div className="detail-panel" role="region" aria-label="Valgt kjøretøy"><div className="detail-top"><span className="eyebrow" style={{color:kinds.find(k=>k.id===selectedNow.kind)?.color}}>{kinds.find(k=>k.id===selectedNow.kind)?.name} · {selectedNow.source}</span><button className="icon-button" onClick={()=>setSelected(null)} aria-label="Lukk kjøretøydetaljer"><X size={19}/></button></div><h2>{selectedNow.name}</h2><p className="detail-destination">{selectedNow.destination||selectedNow.route||"Siste rapporterte posisjon"}</p><div className="detail-values"><div><small>{selectedNow.source==="AIS"?"Fart":"Linje"}</small><strong>{selectedNow.source==="AIS"?(selectedNow.speed===null?"Ukjent":selectedNow.speed.toLocaleString("nb-NO",{maximumFractionDigits:1})+" kn"):selectedNow.line||"–"}</strong></div><div><small>Kurs</small><strong>{selectedNow.bearing===null?"Ukjent":Math.round(selectedNow.bearing)+"°"}</strong></div></div><p className={"position-age"+(oldPosition(selectedNow,now)?" warning":"")}><Clock3 size={15}/>{age(selectedNow.updated,now)}</p>{!selectedNow.updated&&<p className="detail-note">Kilden oppgir ikke tidspunktet for denne posisjonen.</p>}{oldPosition(selectedNow,now)&&<p className="detail-note">Posisjonen er eldre enn 10 minutter og kan ha endret seg.</p>}{(selectedNow.source==="Entur"?bus.error:ais.error)&&<p className="detail-note warning">Datakilden er utilgjengelig. Viser sist mottatte data.</p>}<p className="detail-note">Data hentet {time(selectedNow.fetched)} · {selectedNow.lat.toFixed(4)}° N, {selectedNow.lon.toFixed(4)}° Ø</p><button className="detail-action" onClick={()=>mapRef.current?.focus(selectedNow)}><LocateFixed size={16}/>Sentrer på kartet</button></div>}
 <div className="map-bottom"><div className="view-toolbar"><button onClick={()=>go("Hele området")}><LocateFixed size={17}/><span>Hele området</span></button><i/><button aria-pressed={!three} className={!three?"active":""} onClick={()=>{setThree(false);mapRef.current?.pitch(false);}}>2D</button><button aria-pressed={three} className={three?"active":""} onClick={()=>{setThree(true);mapRef.current?.pitch(true);}}><Layers3 size={16}/>3D</button><i/><button aria-label={full?"Avslutt fullskjerm":"Fullskjerm"} onClick={fullscreen}>{full?<Minimize size={17}/>:<Maximize size={17}/>}</button></div><span className="map-hint">Dra for å utforske · Rull for å zoome</span></div>
 <div className="data-notice">{someError?<><Info size={14}/> {bus.error?"Bussdata utilgjengelig. ":""}{ais.error?"AIS utilgjengelig. ":""}{received?"Viser sist mottatte data.":""}</>:<><Clock3 size={14}/>Siste rapporterte posisjoner · ikke alle kjøretøy sender data</>}</div>
 </section></div>
 <dialog ref={dialog} className="info-dialog"><div className="detail-top"><span className="eyebrow">OM KARTET</span><button className="icon-button" aria-label="Lukk informasjon" onClick={()=>dialog.current?.close()}><X/></button></div><h2>Et blikk på Nordhordland.</h2><p>Kartet samler rapporterte posisjoner for busser og fartøy fra Salhus og Hordvik til Austrheim. Velg et sted, slå kartlag av og på, eller trykk på et kjøretøy.</p><h3>Data og oppdatering</h3><ul><li><a href="https://developer.entur.org/pages-real-time-vehicle/" target="_blank" rel="noreferrer">Entur</a>: bussposisjoner fra Skyss, hentet hvert 30. sekund. Busser som ikke rapporterer posisjon, vises ikke. Posisjoner eldre enn 10 minutter vises dempet.</li><li><a href="https://allemannsdata.com/wiki/kilder/ais/" target="_blank" rel="noreferrer">BarentsWatch / Kystverket via Allemannsdata</a>: siste tilgjengelige AIS-posisjoner, hentet hvert 5. minutt. Posisjonstid kan mangle; hentetid er ikke det samme som posisjonstid. Utvalget kan være begrenset.</li><li><a href="https://allemannsdata.com/wiki/kilder/entur/" target="_blank" rel="noreferrer">Entur via Allemannsdata</a>: avganger. «Sanntid» er oppdatert prognose, «Rutetid» er planlagt tid.</li></ul><h3>Fartøy og kartgrunnlag</h3><p>Ferger omfatter kjente bilferger Storfjord og Fedjebjørn. Andre passasjerfartøy, hurtigbåter og fritidsbåter grupperes etter AIS-type. Reserveferger kan derfor vises under Båter. Posisjonene er rapporterte målinger og flyttes ikke med simulerte bevegelser.</p><p>© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a> · <a href="https://openfreemap.org/" target="_blank" rel="noreferrer">OpenFreeMap</a> · <a href="https://openmaptiles.org/" target="_blank" rel="noreferrer">OpenMapTiles</a>. Terreng fra <a href="https://mapterhorn.com/attribution" target="_blank" rel="noreferrer">Mapterhorn</a>. 3D viser terreng og tilgjengelige bygninger. Kartet er en oversikt, ikke et navigasjonskart.</p></dialog>
 </main>;
}


